spring:
  application:
    name: checkout
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10  #How much time requests remain in buffer (seconds)
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimum-number-of-calls: 20
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 30
        event-consumer-buffer-size: 10
        record-exceptions:
          - java.lang.RuntimeException
  timelimiter:
    configs:
      default:
        timeoutDuration: 500ms
        cancelRunningFuture: true
#  retry:
#    configs:
#      default:
#        max-attempts: 10
#        exponential-backoff-multiplier: 2

